version: '3.7'
services:
  datatlas-back:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - ./src:/src
    command: npm start
    stdin_open: true
