version: '3.7'
services:
  datatlas-back:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 0.0.0.0:3000:4000
    volumes:
      - ./src:/src
    command: npm run dev
    stdin_open: true
