version: '3.7'
services:
  datatlas-back:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "0.0.0.0:3001:3001"
    volumes:
      - ./:/src
    command: npm run dev
    stdin_open: true
